name: barberia
description: Barberia App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  cloud_firestore: ^0.9.0

  flutter:
    sdk: flutter

  flutter_map: ^0.5.0
  meta: ^1.1.6
  firebase_core: ^0.3.0
  firebase_auth: ^0.8.4+1
  flutter_auth_buttons: ^0.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.0.1+1


flutter:

  uses-material-design: true
